stages:
  - build
  - analyze
  - test

.ubuntu-amd64-bionic:
    image: registry.videolan.org/librist-ubuntu-bionic:20200501213126
    stage: build
    tags:
        - docker
        - amd64

.debian-amd64-common:
    image: registry.videolan.org/dav1d-debian-unstable:20200306210534
    stage: build
    tags:
        - docker
        - amd64

build-ubuntu:
    extends: .ubuntu-amd64-bionic
    tags:
        - docker
        - avx2
        - amd64
    script:
        - meson build --buildtype release --werror
        - ninja -C build

build-win64:
    extends: .debian-amd64-common
    script:
        - wineserver -p && wine wineboot
        - meson build --buildtype release
                      --werror
                      --libdir lib
                      --cross-file common/ci/x86_64-w64-mingw32.meson
                      -Ddefault_library=both
        - ninja -C build

build-macos:
    stage: build
    tags:
        - macos
    script:
        - meson build --buildtype release
                      --werror
                      -Ddefault_library=both
        - ninja -C build

analyze-ubuntu:
    stage: analyze
    extends:
        - .ubuntu-amd64-bionic
    needs: ["build-ubuntu"]
    script:
        - meson build --buildtype release --werror -Dstatic_analyze=true
        - ninja -C build analyze

test-ubuntu:
    stage: test
    extends:
        - .ubuntu-amd64-bionic
    needs: ["build-ubuntu"]
    script:
        - meson build --buildtype release --werror -Dtest=true
        - ninja -C build
        - cd build && time meson test -v
