/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ALLOW_INSECURE_IV_FALLBACK 0

#define HAVE_CLOCK_GETTIME 1

#define HAVE_LIBMICROHTTPD 1

#define HAVE_MBEDTLS 0

#define HAVE_NETTLE 0

#define HAVE_PROMETHEUS_SUPPORT 1

#define HAVE_PTHREADS 1

#define HAVE_SOCK_UN_H 1

#define MICROHTTPD_HAS_AUTO_INTERNAL_THREAD 1

#define MICROHTTPD_HAS_RESULT_ENUM 1

